const Article = require('../domain/entities/Article');

class CreateArticle {
  constructor(articleRepository) {
    this.articleRepository = articleRepository;
  }

  async execute(articleData) {
    // In a real application, you'd have more robust validation
    const { title, content, author, categoryId, thumbnailUrl } = articleData;
    if (!title || !content || !author || !categoryId) {
      throw new Error('Missing required fields: title, content, author, or categoryId');
    }

    const article = new Article({
      id: null, // ID will be generated by the database
      title,
      content,
      author,
      categoryId,
      thumbnailUrl,
      createdAt: new Date(),
      updatedAt: new Date()
    });

    return await this.articleRepository.create(article);
  }
}

module.exports = CreateArticle;
